modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "custom_displayname"
version = "${version}"
displayName = "Custom Displayname"
authors = "haedal"
description = '''
Change the name to anything you like!
'''
logoFile = "assets/custom_displayname/icon.png"

[[dependencies.custom_displayname]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.custom_displayname]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.custom_displayname]]
modId = "cloth_config"
type = "required"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "custom_displayname.mixins.json"
